include:
  - project: 'vostok-libraries/ci'
    file: 'template.yml'

variables:
  CEMENT_MODULE: 'vostok.clusterclient.transport'
  GITHUB_REPO: 'git@github.com:vostok/clusterclient.transport'
  PUBLISH: 'NUGET_ORG'
  PUBLISH_KEY: $NUGET_ORG_VOSTOK_APIKEY
  TARGET_FRAMEWORKS: "net6.0 net5.0 netcoreapp3.1 netcoreapp2.1 net471"