//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Http.Net.Http.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file length was too large for the file system..
        /// </summary>
        public static string ArgumentOutOfRange_FileLengthTooBig {
            get {
                return "ArgumentOutOfRange_FileLengthTooBig";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative number required..
        /// </summary>
        public static string ArgumentOutOfRange_NeedNonNegativeNum {
            get {
                return "ArgumentOutOfRange_NeedNonNegativeNum";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive number required..
        /// </summary>
        public static string ArgumentOutOfRange_NeedPosNum {
            get {
                return "ArgumentOutOfRange_NeedPosNum";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned {1}..
        /// </summary>
        public static string event_OperationReturnedSomething {
            get {
                return "event_OperationReturnedSomething";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in header name..
        /// </summary>
        public static string InvalidHeaderName {
            get {
                return "InvalidHeaderName";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists..
        /// </summary>
        public static string IO_FileExists_Name {
            get {
                return "IO_FileExists_Name";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified file..
        /// </summary>
        public static string IO_FileNotFound {
            get {
                return "IO_FileNotFound";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        public static string IO_FileNotFound_FileName {
            get {
                return "IO_FileNotFound_FileName";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path..
        /// </summary>
        public static string IO_PathNotFound_NoPathName {
            get {
                return "IO_PathNotFound_NoPathName";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;..
        /// </summary>
        public static string IO_PathNotFound_Path {
            get {
                return "IO_PathNotFound_Path";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file name or path is too long, or a component of the specified path is too long..
        /// </summary>
        public static string IO_PathTooLong {
            get {
                return "IO_PathTooLong";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; is too long, or a component of the specified path is too long..
        /// </summary>
        public static string IO_PathTooLong_Path {
            get {
                return "IO_PathTooLong_Path";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to move the position before the beginning of the stream..
        /// </summary>
        public static string IO_SeekBeforeBegin {
            get {
                return "IO_SeekBeforeBegin";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file &apos;{0}&apos; because it is being used by another process..
        /// </summary>
        public static string IO_SharingViolation_File {
            get {
                return "IO_SharingViolation_File";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file because it is being used by another process..
        /// </summary>
        public static string IO_SharingViolation_NoFileName {
            get {
                return "IO_SharingViolation_NoFileName";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string is not in the form required for an e-mail address..
        /// </summary>
        public static string MailAddressInvalidFormat {
            get {
                return "MailAddressInvalidFormat";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in the mail header: &apos;{0}&apos;..
        /// </summary>
        public static string MailHeaderFieldInvalidCharacter {
            get {
                return "MailHeaderFieldInvalidCharacter";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail header is malformed..
        /// </summary>
        public static string MailHeaderFieldMalformedHeader {
            get {
                return "MailHeaderFieldMalformedHeader";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error: A received message contains a valid signature but it was not encrypted as required by the effective Protection Level..
        /// </summary>
        public static string net_auth_message_not_encrypted {
            get {
                return "net_auth_message_not_encrypted";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed on a completed asynchronous result object..
        /// </summary>
        public static string net_completed_result {
            get {
                return "net_completed_result";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient buffer space. Required: {0} Actual: {1}..
        /// </summary>
        public static string net_context_buffer_too_small {
            get {
                return "net_context_buffer_too_small";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos;=&apos;{1}&apos; part of the cookie is invalid..
        /// </summary>
        public static string net_cookie_attribute {
            get {
                return "net_cookie_attribute";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTLM authentication requires the GSSAPI plugin &apos;gss-ntlmssp&apos;..
        /// </summary>
        public static string net_gssapi_ntlm_missing_plugin {
            get {
                return "net_gssapi_ntlm_missing_plugin";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with status: {0} (Minor status: {1})..
        /// </summary>
        public static string net_gssapi_operation_failed {
            get {
                return "net_gssapi_operation_failed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with error - {0} ({1})..
        /// </summary>
        public static string net_gssapi_operation_failed_detailed {
            get {
                return "net_gssapi_operation_failed_detailed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with error - {0}..
        /// </summary>
        public static string net_gssapi_operation_failed_detailed_majoronly {
            get {
                return "net_gssapi_operation_failed_detailed_majoronly";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with status: {0}..
        /// </summary>
        public static string net_gssapi_operation_failed_majoronly {
            get {
                return "net_gssapi_operation_failed_majoronly";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        public static string net_http_argument_empty_string {
            get {
                return "net_http_argument_empty_string";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed because the connection could not be reused..
        /// </summary>
        public static string net_http_authconnectionfailure {
            get {
                return "net_http_authconnectionfailure";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer was not long enough..
        /// </summary>
        public static string net_http_buffer_insufficient_length {
            get {
                return "net_http_buffer_insufficient_length";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Transfer-Encoding: chunked&apos; header can not be used when content object is not specified..
        /// </summary>
        public static string net_http_chunked_not_allowed_with_empty_content {
            get {
                return "net_http_chunked_not_allowed_with_empty_content";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base address must be an absolute URI..
        /// </summary>
        public static string net_http_client_absolute_baseaddress_required {
            get {
                return "net_http_client_absolute_baseaddress_required";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the request..
        /// </summary>
        public static string net_http_client_execution_error {
            get {
                return "net_http_client_execution_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;http&apos; and &apos;https&apos; schemes are allowed..
        /// </summary>
        public static string net_http_client_http_baseaddress_required {
            get {
                return "net_http_client_http_baseaddress_required";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set..
        /// </summary>
        public static string net_http_client_invalid_requesturi {
            get {
                return "net_http_client_invalid_requesturi";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request message was already sent. Cannot send the same request message multiple times..
        /// </summary>
        public static string net_http_client_request_already_sent {
            get {
                return "net_http_client_request_already_sent";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write more bytes to the buffer than the configured maximum buffer size: {0}..
        /// </summary>
        public static string net_http_content_buffersize_exceeded {
            get {
                return "net_http_content_buffersize_exceeded";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering more than {0} bytes is not supported..
        /// </summary>
        public static string net_http_content_buffersize_limit {
            get {
                return "net_http_content_buffersize_limit";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field cannot be longer than {0} characters..
        /// </summary>
        public static string net_http_content_field_too_long {
            get {
                return "net_http_content_field_too_long";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set..
        /// </summary>
        public static string net_http_content_invalid_charset {
            get {
                return "net_http_content_invalid_charset";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support concurrent read operations..
        /// </summary>
        public static string net_http_content_no_concurrent_reads {
            get {
                return "net_http_content_no_concurrent_reads";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async operation did not return a System.Threading.Tasks.Task object..
        /// </summary>
        public static string net_http_content_no_task_returned {
            get {
                return "net_http_content_no_task_returned";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support writing..
        /// </summary>
        public static string net_http_content_readonly_stream {
            get {
                return "net_http_content_readonly_stream";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream was already consumed. It cannot be read again..
        /// </summary>
        public static string net_http_content_stream_already_read {
            get {
                return "net_http_content_stream_already_read";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while copying content to a stream..
        /// </summary>
        public static string net_http_content_stream_copy_error {
            get {
                return "net_http_content_stream_copy_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements is greater than the available space from arrayIndex to the end of the destination array..
        /// </summary>
        public static string net_http_copyto_array_too_small {
            get {
                return "net_http_copyto_array_too_small";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object was disposed while operations were in progress..
        /// </summary>
        public static string net_http_disposed_while_in_use {
            get {
                return "net_http_disposed_while_in_use";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using this feature requires Windows 10 Version 1607..
        /// </summary>
        public static string net_http_feature_requires_Windows10Version1607 {
            get {
                return "net_http_feature_requires_Windows10Version1607";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate was not found in the personal (\&quot;MY\&quot;) certificate store. In UWP, client certificates are only supported if they have been added to that certificate store..
        /// </summary>
        public static string net_http_feature_UWPClientCertSupportRequiresCertInPersonalCertificateStore {
            get {
                return "net_http_feature_UWPClientCertSupportRequiresCertInPersonalCertificateStore";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request message must be provided. It cannot be null..
        /// </summary>
        public static string net_http_handler_norequest {
            get {
                return "net_http_handler_norequest";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler did not return a response message..
        /// </summary>
        public static string net_http_handler_noresponse {
            get {
                return "net_http_handler_noresponse";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inner handler has not been assigned..
        /// </summary>
        public static string net_http_handler_not_assigned {
            get {
                return "net_http_handler_not_assigned";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid quoted string..
        /// </summary>
        public static string net_http_headers_invalid_etag_name {
            get {
                return "net_http_headers_invalid_etag_name";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid &apos;From&apos; header string..
        /// </summary>
        public static string net_http_headers_invalid_from_header {
            get {
                return "net_http_headers_invalid_from_header";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header name format is invalid..
        /// </summary>
        public static string net_http_headers_invalid_header_name {
            get {
                return "net_http_headers_invalid_header_name";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid &apos;Host&apos; header string..
        /// </summary>
        public static string net_http_headers_invalid_host_header {
            get {
                return "net_http_headers_invalid_host_header";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range. At least one of the two parameters must not be null..
        /// </summary>
        public static string net_http_headers_invalid_range {
            get {
                return "net_http_headers_invalid_range";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string net_http_headers_invalid_value {
            get {
                return "net_http_headers_invalid_value";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-line characters in header values must be followed by a white-space character..
        /// </summary>
        public static string net_http_headers_no_newlines {
            get {
                return "net_http_headers_no_newlines";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects..
        /// </summary>
        public static string net_http_headers_not_allowed_header_name {
            get {
                return "net_http_headers_not_allowed_header_name";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given header was not found..
        /// </summary>
        public static string net_http_headers_not_found {
            get {
                return "net_http_headers_not_found";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add value because header &apos;{0}&apos; does not support multiple values..
        /// </summary>
        public static string net_http_headers_single_value_header {
            get {
                return "net_http_headers_single_value_header";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPACK integer exceeds limits or has an overlong encoding..
        /// </summary>
        public static string net_http_hpack_bad_integer {
            get {
                return "net_http_hpack_bad_integer";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huffman-coded literal string failed to decode..
        /// </summary>
        public static string net_http_hpack_huffman_decode_failed {
            get {
                return "net_http_hpack_huffman_decode_failed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete header block received..
        /// </summary>
        public static string net_http_hpack_incomplete_header_block {
            get {
                return "net_http_hpack_incomplete_header_block";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic table size update received after beginning of header block..
        /// </summary>
        public static string net_http_hpack_late_dynamic_table_size_update {
            get {
                return "net_http_hpack_late_dynamic_table_size_update";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP/2 server sent invalid data on the connection. HTTP/2 error code &apos;{0}&apos; (0x{1})..
        /// </summary>
        public static string net_http_http2_connection_error {
            get {
                return "net_http_http2_connection_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP/2 server reset the stream. HTTP/2 error code &apos;{0}&apos; (0x{1})..
        /// </summary>
        public static string net_http_http2_stream_error {
            get {
                return "net_http_http2_stream_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the HTTP method is invalid..
        /// </summary>
        public static string net_http_httpmethod_format_error {
            get {
                return "net_http_httpmethod_format_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP method &apos;{0}&apos; is not supported on this platform..
        /// </summary>
        public static string net_http_httpmethod_notsupported_error {
            get {
                return "net_http_httpmethod_notsupported_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using CookieUsePolicy.UseSpecifiedCookieContainer, the CookieContainer property must not be null..
        /// </summary>
        public static string net_http_invalid_cookiecontainer {
            get {
                return "net_http_invalid_cookiecontainer";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property must be set to &apos;{1}&apos; to use this property..
        /// </summary>
        public static string net_http_invalid_enable_first {
            get {
                return "net_http_invalid_enable_first";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using WindowsProxyUsePolicy.UseCustomProxy, the Proxy property must not be null..
        /// </summary>
        public static string net_http_invalid_proxy {
            get {
                return "net_http_invalid_proxy";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &apos;http&apos; scheme is allowed for proxies..
        /// </summary>
        public static string net_http_invalid_proxy_scheme {
            get {
                return "net_http_invalid_proxy_scheme";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy..
        /// </summary>
        public static string net_http_invalid_proxyusepolicy {
            get {
                return "net_http_invalid_proxyusepolicy";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid or unrecognized response..
        /// </summary>
        public static string net_http_invalid_response {
            get {
                return "net_http_invalid_response";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid chunk extension: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_chunk_extension_invalid {
            get {
                return "net_http_invalid_response_chunk_extension_invalid";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received chunk header length could not be parsed: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_chunk_header_invalid {
            get {
                return "net_http_invalid_response_chunk_header_invalid";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid chunk terminator: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_chunk_terminator_invalid {
            get {
                return "net_http_invalid_response_chunk_terminator_invalid";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid folded header..
        /// </summary>
        public static string net_http_invalid_response_header_folder {
            get {
                return "net_http_invalid_response_header_folder";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid header line: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_header_line {
            get {
                return "net_http_invalid_response_header_line";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid header name: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_header_name {
            get {
                return "net_http_invalid_response_header_name";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response ended prematurely..
        /// </summary>
        public static string net_http_invalid_response_premature_eof {
            get {
                return "net_http_invalid_response_premature_eof";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response ended prematurely, with at least {0} additional bytes expected..
        /// </summary>
        public static string net_http_invalid_response_premature_eof_bytecount {
            get {
                return "net_http_invalid_response_premature_eof_bytecount";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an HTTP/2 pseudo-header as a trailing header..
        /// </summary>
        public static string net_http_invalid_response_pseudo_header_in_trailer {
            get {
                return "net_http_invalid_response_pseudo_header_in_trailer";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid status code: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_status_code {
            get {
                return "net_http_invalid_response_status_code";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid status line: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_status_line {
            get {
                return "net_http_invalid_response_status_line";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received status phrase could not be decoded with iso-8859-1: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_invalid_response_status_reason {
            get {
                return "net_http_invalid_response_status_reason";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read operation failed, see inner exception..
        /// </summary>
        public static string net_http_io_read {
            get {
                return "net_http_io_read";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from the transport connection. The connection was closed before all data could be read. Expected {0} bytes, read {1} bytes..
        /// </summary>
        public static string net_http_io_read_incomplete {
            get {
                return "net_http_io_read_incomplete";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The write operation failed, see inner exception..
        /// </summary>
        public static string net_http_io_write {
            get {
                return "net_http_io_write";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support custom handling of certificates on this operating system. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_callback_notsupported_os {
            get {
                return "net_http_libcurl_callback_notsupported_os";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support custom handling of certificates with this combination of libcurl ({0}) and its SSL backend (&quot;{1}&quot;). An SSL backend based on &quot;{2}&quot; is required. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_callback_notsupported_sslbackend {
            get {
                return "net_http_libcurl_callback_notsupported_sslbackend";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support client authentication certificates on this operating system. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_clientcerts_notsupported_os {
            get {
                return "net_http_libcurl_clientcerts_notsupported_os";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support client authentication certificates with this combination of libcurl ({0}) and its SSL backend (&quot;{1}&quot;). An SSL backend based on &quot;{2}&quot; is required. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_clientcerts_notsupported_sslbackend {
            get {
                return "net_http_libcurl_clientcerts_notsupported_sslbackend";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support changing revocation settings with this combination of libcurl ({0}) and its SSL backend (&quot;{1}&quot;). An SSL backend based on &quot;{2}&quot; is required. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_revocation_notsupported_sslbackend {
            get {
                return "net_http_libcurl_revocation_notsupported_sslbackend";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;q&apos; value is invalid: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_log_headers_invalid_quality {
            get {
                return "net_http_log_headers_invalid_quality";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for header &apos;{0}&apos; contains invalid new-line characters. Value: &apos;{1}&apos;..
        /// </summary>
        public static string net_http_log_headers_no_newlines {
            get {
                return "net_http_log_headers_no_newlines";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid email address. Error: {1}.
        /// </summary>
        public static string net_http_log_headers_wrong_email_format {
            get {
                return "net_http_log_headers_wrong_email_format";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response status code does not indicate success: {0} ({1})..
        /// </summary>
        public static string net_http_message_not_success_statuscode {
            get {
                return "net_http_message_not_success_statuscode";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support concurrent I/O read or write operations..
        /// </summary>
        public static string net_http_no_concurrent_io_allowed {
            get {
                return "net_http_no_concurrent_io_allowed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance has already started one or more requests. Properties can only be modified before sending the first request..
        /// </summary>
        public static string net_http_operation_started {
            get {
                return "net_http_operation_started";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid Base64 string. Error: {1}.
        /// </summary>
        public static string net_http_parser_invalid_base64_string {
            get {
                return "net_http_parser_invalid_base64_string";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason phrase must not contain new-line characters..
        /// </summary>
        public static string net_http_reasonphrase_format_error {
            get {
                return "net_http_reasonphrase_format_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was aborted..
        /// </summary>
        public static string net_http_request_aborted {
            get {
                return "net_http_request_aborted";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request headers must contain only ASCII characters..
        /// </summary>
        public static string net_http_request_invalid_char_encoding {
            get {
                return "net_http_request_invalid_char_encoding";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT request must contain Host header..
        /// </summary>
        public static string net_http_request_no_host {
            get {
                return "net_http_request_no_host";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP response headers length exceeded the set limit of {0} bytes..
        /// </summary>
        public static string net_http_response_headers_exceeded_length {
            get {
                return "net_http_response_headers_exceeded_length";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server shut down the connection..
        /// </summary>
        public static string net_http_server_shutdown {
            get {
                return "net_http_server_shutdown";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSL connection could not be established, see inner exception..
        /// </summary>
        public static string net_http_ssl_connection_failed {
            get {
                return "net_http_ssl_connection_failed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler was disposed of while active operations were in progress..
        /// </summary>
        public static string net_http_unix_handler_disposed {
            get {
                return "net_http_unix_handler_disposed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The libcurl library in use ({0}) does not support HTTPS..
        /// </summary>
        public static string net_http_unix_https_support_unavailable_libcurl {
            get {
                return "net_http_unix_https_support_unavailable_libcurl";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The libcurl library in use ({0}) does not support different credentials for different authentication schemes..
        /// </summary>
        public static string net_http_unix_invalid_credential {
            get {
                return "net_http_unix_invalid_credential";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP 1.0 does not support chunking..
        /// </summary>
        public static string net_http_unsupported_chunking {
            get {
                return "net_http_unsupported_chunking";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request HttpVersion 0.X is not supported.  Use 1.0 or above..
        /// </summary>
        public static string net_http_unsupported_version {
            get {
                return "net_http_unsupported_version";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username for a credential object cannot be null or empty..
        /// </summary>
        public static string net_http_username_empty_string {
            get {
                return "net_http_username_empty_string";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value must be greater than {0}..
        /// </summary>
        public static string net_http_value_must_be_greater_than {
            get {
                return "net_http_value_must_be_greater_than";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not supported for property &apos;{1}&apos;..
        /// </summary>
        public static string net_http_value_not_supported {
            get {
                return "net_http_value_not_supported";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} calling {1}, &apos;{2}&apos;..
        /// </summary>
        public static string net_http_winhttp_error {
            get {
                return "net_http_winhttp_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not valid in the &apos;{0}&apos; enumeration..
        /// </summary>
        public static string net_invalid_enum {
            get {
                return "net_invalid_enum";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed with error {1}..
        /// </summary>
        public static string net_log_operation_failed_with_error {
            get {
                return "net_log_operation_failed_with_error";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not implemented by this class..
        /// </summary>
        public static string net_MethodNotImplementedException {
            get {
                return "net_MethodNotImplementedException";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name should be non empty if default credentials are passed..
        /// </summary>
        public static string net_nego_not_supported_empty_target_with_defaultcreds {
            get {
                return "net_nego_not_supported_empty_target_with_defaultcreds";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested protection level is not supported with the GSSAPI implementation currently installed..
        /// </summary>
        public static string net_nego_protection_level_not_supported {
            get {
                return "net_nego_protection_level_not_supported";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server implementation is not supported.
        /// </summary>
        public static string net_nego_server_not_supported {
            get {
                return "net_nego_server_not_supported";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTLM authentication is not possible with default credentials on this platform..
        /// </summary>
        public static string net_ntlm_not_possible_default_cred {
            get {
                return "net_ntlm_not_possible_default_cred";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested security package is not supported..
        /// </summary>
        public static string net_securitypackagesupport {
            get {
                return "net_securitypackagesupport";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested security protocol is not supported..
        /// </summary>
        public static string net_securityprotocolnotsupported {
            get {
                return "net_securityprotocolnotsupported";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application protocol list is invalid..
        /// </summary>
        public static string net_ssl_app_protocols_invalid {
            get {
                return "net_ssl_app_protocols_invalid";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/2 requires TLS 1.2 or newer, but &apos;{0}&apos; was negotiated..
        /// </summary>
        public static string net_ssl_http2_requires_tls12 {
            get {
                return "net_ssl_http2_requires_tls12";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        public static string NotSupported_UnreadableStream {
            get {
                return "NotSupported_UnreadableStream";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        public static string NotSupported_UnwritableStream {
            get {
                return "NotSupported_UnwritableStream";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed stream..
        /// </summary>
        public static string ObjectDisposed_StreamClosed {
            get {
                return "ObjectDisposed_StreamClosed";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported handle type..
        /// </summary>
        public static string SSPIInvalidHandleType {
            get {
                return "SSPIInvalidHandleType";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path is denied..
        /// </summary>
        public static string UnauthorizedAccess_IODenied_NoPathName {
            get {
                return "UnauthorizedAccess_IODenied_NoPathName";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path &apos;{0}&apos; is denied..
        /// </summary>
        public static string UnauthorizedAccess_IODenied_Path {
            get {
                return "UnauthorizedAccess_IODenied_Path";
            }
        }
    }
}
